create table if not exists public.service_reviews (
  id bigint generated by default as identity primary key,
  created_at timestamp(3) without time zone not null default (now() at time zone 'Asia/Ho_Chi_Minh'),
  submitted_at_vietnam timestamp(3) not null default (now() at time zone 'Asia/Ho_Chi_Minh'),
  rating smallint not null check (rating between 1 and 5),
  impressions text[] not null default '{}',
  impression_note text not null default '',
  dissatisfactions text[] not null default '{}',
  dissatisfaction_note text not null default '',
  customer_name text not null default '',
  phone text not null,
  store text not null default 'LUSH Vincom Đồng Khởi',
  consent_to_contact boolean not null default false
);

alter table public.service_reviews enable row level security;

drop policy if exists "review inserts through server" on public.service_reviews;
create policy "review inserts through server"
  on public.service_reviews
  for insert
  with check (true);

alter table public.service_reviews
  alter column store set default 'LUSH Vincom Đồng Khởi';

alter table public.service_reviews
  add column if not exists impression_note text not null default '';

alter table public.service_reviews
  add column if not exists submitted_at_vietnam timestamp(3) not null default (now() at time zone 'Asia/Ho_Chi_Minh');

drop view if exists public.review_summary;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'service_reviews'
      and column_name = 'created_at'
      and data_type = 'timestamp with time zone'
  ) then
    alter table public.service_reviews alter column created_at drop default;
    alter table public.service_reviews
      alter column created_at type timestamp(3) without time zone
      using created_at at time zone 'Asia/Ho_Chi_Minh';
    alter table public.service_reviews
      alter column created_at set default (now() at time zone 'Asia/Ho_Chi_Minh');
  end if;
end $$;

update public.service_reviews
set submitted_at_vietnam = created_at;

update public.service_reviews
set impressions = array(
  select case item
    when 'service' then 'Dịch vụ cửa hàng'
    when 'space' then 'Không gian cửa hàng'
    when 'team' then 'Thái độ nhân viên'
    when 'product-range' then 'Sản phẩm đa dạng'
    when 'other' then 'Khác'
    else item
  end
  from unnest(impressions) as item
);

create view public.review_summary as
select
  id,
  created_at,
  rating,
  impressions,
  impression_note,
  dissatisfactions,
  dissatisfaction_note,
  customer_name,
  phone,
  store,
  consent_to_contact,
  submitted_at_vietnam::timestamp(6) as submitted_at_vietnam
from public.service_reviews;

comment on view public.review_summary is 'Tổng hợp đánh giá dịch vụ khách hàng LUSH - text tiếng Việt và giờ Việt Nam';

-- The Node.js server connects with DATABASE_URL. Never expose DATABASE_URL in VITE_ variables.
