create table if not exists public.service_reviews (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  rating smallint not null check (rating between 1 and 5),
  impressions text[] not null default '{}',
  impression_note text not null default '',
  dissatisfactions text[] not null default '{}',
  dissatisfaction_note text not null default '',
  customer_name text not null default '',
  phone text not null,
  store text not null default 'LUSH Vincom Đồng Khởi',
  consent_to_contact boolean not null default false
);

alter table public.service_reviews enable row level security;

drop policy if exists "review inserts through server" on public.service_reviews;
create policy "review inserts through server"
  on public.service_reviews
  for insert
  with check (true);

alter table public.service_reviews
  alter column store set default 'LUSH Vincom Đồng Khởi';

alter table public.service_reviews
  add column if not exists impression_note text not null default '';

create or replace view public.review_summary as
select
  id,
  created_at,
  rating,
  impressions,
  impression_note,
  dissatisfactions,
  dissatisfaction_note,
  customer_name,
  phone,
  store,
  consent_to_contact,
  created_at at time zone 'Asia/Ho_Chi_Minh' as submitted_at_vietnam
from public.service_reviews;

comment on view public.review_summary is 'Tổng hợp đánh giá dịch vụ khách hàng LUSH';

-- The Node.js server connects with DATABASE_URL. Never expose DATABASE_URL in VITE_ variables.
